version: "3"

services:
  web:
    image: "khalidait/khalid:tian_web"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - webVolume:/data
    networks:
      - mainNetwork
    deploy:
      replicas: 1

volumes:
  webVolume:

networks:
  mainNetwork:
