version: "3"

services:
  web:
    image: "khalidait/khalid:tian_bind"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - bindVolume:/data
    networks:
      - mainNetwork
    deploy:
      replicas: 1

volumes:
  bindVolume:

networks:
  mainNetwork:
