version: "3.8"

services:
  web:
    image: "khalid:tian_web"
    build: .
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - type: volume
        source: webVolume
        target: /data
        volume:
          nocopy: true
    networks:
      - mainNetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: always

volumes:
  web_volume:

networks:
  mainNetwork:
