version: "3"

services:
  web:
    image: "tian_web:last"
    build: .
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - type: volume
        source: web_volume
        target: /data
        volume:
          nocopy: true
    networks:
      - mainNetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: always
volumes:
  web_volume:
